export const courseCategories = [
  {
    id: 1,
    title: "Python Full Stack Development",
    price: "₹15,000 + ₹10,000 placement",
    image: "/Python-Full-Stack-image.jpg",
    subCourses: [
      "Frontend: HTML, CSS, JavaScript, React.js",
      "Backend: Django / Flask",
      "Database: MySQL / PostgreSQL / MongoDB",
      "Version Control: Git & GitHub",
      "Deployment: AWS / Heroku",
    ],
  },
  {
    id: 2,
    title: "MERN Stack Development",
    price: "₹20,000 + ₹10,000 placement",
    image: "/Mern-Stack-Developer.png",
    subCourses: [
      "MongoDB (Database)",
      "Express.js (Backend Framework)",
      "React.js (Frontend Library)",
      "Node.js (Backend Runtime)",
      "Deployment & Hosting (AWS, Vercel, Heroku)",
    ],
  },
  {
    id: 3,
    title: "MEAN Stack Development",
    price: "₹20,000 + ₹10,000 placement",
    image: "/MEAN_stack.jpg",
    subCourses: [
      "MongoDB (Database)",
      "Express.js (Backend Framework)",
      "Angular (Frontend Framework)",
      "Node.js (Backend Runtime)",
      "Deployment & Hosting",
    ],
  },
  {
    id: 4,
    title: "JAVA Stack Development",
    price: "₹20,000 + ₹10,000 placement",
    image: "/java_stack_development.jpeg",
    subCourses: [
      "Core Java & Advanced Java",
      "Spring Boot Framework",
      "Hibernate & JPA",
      "Frontend: HTML, CSS, JavaScript, React/Angular",
      "Database: MySQL / PostgreSQL",
    ],
  },
  {
    id: 5,
    title: "PHP Stack Development",
    price: "₹20,000 + ₹10,000 placement",
    image: "/web3.jpeg",
    subCourses: [
      "Core PHP & Advanced PHP",
      "Laravel Framework",
      "Frontend: HTML, CSS, JavaScript, Bootstrap",
      "Database: MySQL",
      "CMS Development: WordPress",
    ],
  },
  {
    id: 6,
    title: "Web Development",
    price: "₹7,000",
    image: "/web_development.webp",
    subCourses: [
      "Frontend Development: HTML, CSS, JavaScript, Bootstrap, React.js",
      "Backend Development: Node.js, Django, PHP, Laravel",
      "WordPress Development",
    ],
  },
  {
    id: 7,
    title: "Data Science & Machine Learning",
    price: "₹20,000 + ₹10,000 placement",
    image: "/machineLearning.jpg",
    subCourses: [
      "Data Science with Python",
      "Machine Learning & AI",
      "Deep Learning with TensorFlow & Keras",
      "Business Analytics",
      "Data Analytics",
    ],
  },
  {
    id: 8,
    title: "Mobile App Development",
    price: "₹20,000 + ₹10,000 placement",
    image: "/mobileAppDevelopment.png",
    subCourses: [
      "Flutter Development",
      "Android Development (Java/Kotlin)",
      "iOS Development (Swift)",
      "React Native Development",
    ],
  },
  {
    id: 9,
    title: "Cyber Security & Ethical Hacking",
    price: "₹20,000 + ₹10,000 placement",
    image: "/ethicalHacking.jpg",
    subCourses: [
      "Ethical Hacking & Penetration Testing",
      "Cyber Security Essentials",
      "Bug Bounty",
    ],
  },
  {
    id: 10,
    title: "UI/UX Design",
    price: "₹10,000 + ₹10,000 placement",
    image: "/ui-ux.jpg",
    subCourses: [
      "Adobe XD",
      "Figma",
      "Sketch",
      "Wireframing & Prototyping",
      "User Research & Usability Testing",
    ],
  },
  {
    id: 11,
    title: "DevOps & Cloud Computing",
    price: "₹10,000 + ₹10,000 placement",
    image: "/cloudComputing.jpg",
    subCourses: [
      "AWS Cloud Computing",
      "DevOps (Docker, Kubernetes, Jenkins, Git, CI/CD)",
      "Linux & Shell Scripting",
      "Azure & Google Cloud Basics",
    ],
  },
  {
    id: 12,
    title: "Artificial Intelligence (AI) & Automation",
    price: "₹50,000 + ₹10,000 placement",
    image: "/ai.png",
    subCourses: [
      "AI Full Stack Development",
      "Chatbot Development (OpenAI, LangChain)",
      "RPA (Robotic Process Automation)",
      "Generative AI Applications",
    ],
  },
  {
    id: 13,
    title: "Software Testing & QA",
    price: "₹10,000 + ₹10,000 placement",
    image: "/testing.webp",
    subCourses: [
      "Manual Testing",
      "Automation Testing (Selenium, Cypress, JUnit, PyTest)",
      "API Testing",
      "Performance Testing",
    ],
  },
  {
    id: 14,
    title: "Database Management",
    price: "₹50,000 placement",
    image: "/db.jpeg",
    subCourses: [
      "SQL (MySQL, PostgreSQL, SQL Server)",
      "NoSQL (MongoDB, Firebase)",
      "Database Design & Normalization",
      "Database Security & Backup",
    ],
  },
  {
    id: 15,
    title: "Internship & IT Experience Programs",
    price: "₹10,000 placement",
    image: "/internship.png",
    subCourses: [
      "Live Project Internship",
      "Job-Oriented Training with Experience Certificates",
      "Real-World IT Experience",
    ],
  },
];
